
/**
 * Enum class to represent the different types of events that can be generated by the WatchService.
 */
public enum EventType {
    FILECREATED, FILEDELETED, FILEMODIFIED, FILERENAMED, DIRECTORYCREATED, DIRECTORYDELETED, DIRECTORYRENAMED;
}
